/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorIngreso;
import Modelo.ModeloIngreso;

/**
 *
 * @author Cindy Ruano
 */
public class VistaIngreso extends javax.swing.JFrame {

    /**
     * Creates new form VistaIngreso
     */
    public VistaIngreso() {
        initComponents();
        
        setLocationRelativeTo(null);
        Modelo.ModeloIngreso modelo = new ModeloIngreso(this);
        
        Controlador.ControladorIngreso controlador2 = new ControladorIngreso (modelo);
        setControlador(controlador2);
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        txtDatos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnDatos = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        btnCalcular = new javax.swing.JPanel();
        letCalcular = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnQuitar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fondoIngreso = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        contenedor2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 530));

        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatos.setSelectionColor(new java.awt.Color(235, 200, 200));
        fondoPanel.add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Datos:");
        fondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MEDIDAS DE TENDENCIA CENTRAL");
        fondoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 470, -1));
        fondoPanel.add(spnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 370, 230));
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 83, 330, 10));

        btnCalcular.setBackground(new java.awt.Color(182, 123, 123));
        btnCalcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        btnCalcular.setMinimumSize(new java.awt.Dimension(70, 30));
        btnCalcular.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letCalcular.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        letCalcular.setForeground(new java.awt.Color(255, 255, 255));
        letCalcular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letCalcular.setText("Calcular");
        letCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.add(letCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        fondoPanel.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 40));

        btnOrdenar.setBackground(new java.awt.Color(182, 123, 123));
        btnOrdenar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        btnOrdenar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ordenar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 20));

        fondoPanel.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 40));

        btnQuitar.setBackground(new java.awt.Color(182, 123, 123));
        btnQuitar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        btnQuitar.setPreferredSize(new java.awt.Dimension(50, 30));
        btnQuitar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quitar");
        btnQuitar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        fondoPanel.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 70, 30));

        btnAgregar.setBackground(new java.awt.Color(182, 123, 123));
        btnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        btnAgregar.setMinimumSize(new java.awt.Dimension(60, 30));
        btnAgregar.setPreferredSize(new java.awt.Dimension(50, 30));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar");
        btnAgregar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        fondoPanel.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, -1));

        btnLimpiar.setBackground(new java.awt.Color(182, 123, 123));
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(70, 30));
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Limpiar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, -1));

        fondoPanel.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 70, 40));

        fondoIngreso.setBackground(new java.awt.Color(218, 165, 165));
        fondoIngreso.setOpaque(true);
        fondoPanel.add(fondoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 530));

        contenedor.setBackground(new java.awt.Color(235, 200, 200));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoPanel.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 530, 530));

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoPanel.add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnCalcular;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnOrdenar;
    public javax.swing.JPanel btnQuitar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JLabel fondoIngreso;
    private javax.swing.JPanel fondoPanel;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel letCalcular;
    private javax.swing.JSpinner spnDatos;
    private javax.swing.JTextField txtDatos;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorIngreso controlador){
    this.addWindowListener(controlador);
        btnAgregar.addMouseListener(controlador);
        btnCalcular.addMouseListener(controlador);
        btnLimpiar.addMouseListener(controlador);
        btnOrdenar.addMouseListener(controlador);
        btnQuitar.addMouseListener(controlador);

    }
}
